### ISSUE TITLE
Failed to open the plugin manifest

### ISSUE THREAD

**Issue by poloyacero** [traefik/plugindemo#16]
**Context:**
I tried to run the plugindemo in localmode following the necessary instructions in the documentation - https://github.com/traefik/plugindemo#local-mode

<details>
<summary>Static Config</summary>

```yml
entryPoints:
  web:
    address: :9000
api:
  dashboard: true
  insecure: true
log:
  level: DEBUG
experimental:
  localPlugins:
    example:
      moduleName: github.com/traefik/plugindemo
providers:
  file:
    filename: dynamic_config.yaml
```

</details>

<details>
<summary>Dynamic Config</summary>

```yml
http:
  routers:
    my-router:
      rule: Path(`/`)
      service: service-foo
      entryPoints:
        - web
      middlewares:
        - testHeader
  services:
   service-foo:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:5000/
  middlewares:
    my-plugin:
      plugin:
        example:
          headers:
            Foo: Bar
```

</details>

Issue:

```
time="2022-10-05T10:43:12+04:00" level=error msg="Plugins are disabled because an error has occurred." error="1 error occurred:\n\t* failed to open the plugin manifest plugins-local\\src\\github.com\\traefik\\plugindemo\\.traefik.yml: open plugins-local\\src\\github.com\\traefik\\plugindemo\\.traefik.yml: The system cannot find the path specified.\n\n"

time="2022-10-05T10:43:13+04:00" level=error msg="invalid middleware \"my-plugin@file\" configuration: invalid middleware type or middleware does not exist" entryPointName=web routerName=my-router@file
```

<details>
<summary>Directory structure</summary>

![image](https://user-images.githubusercontent.com/9990246/194043086-f08f5433-594e-442e-a6ce-5c0833b48da6.png)
![image](https://user-images.githubusercontent.com/9990246/194043637-226579da-46f4-43d7-a038-4a0c66289b00.png)

</details>

Traefik version: 2.8.7

Is there something that I missed? Please let me know. Thanks.
